### ISSUE TITLE
issue with end_avi and index file

### ISSUE THREAD

**Issue by oscar3788** [jameszah/CameraWebServerRecorder#4]
Hi Jameszah,

I'm trying to use your code as a demo for my personal project but I have a problem.
When I finish to record a video and it's saved in the SD card succesfully, there is some problem with the avi file and the index.
For some reason is working good if the video is played with a computer but always corrupt if I play with android device with vlc payer. The message is always the same, the index of avi file is missing or corrupt. 

My knowledge is not enought to understand completally  the end_avi function and adapt a fix for this case.
Can you tell me if is a known situation for you? or what part of the code can I check to resolve this situation ?
Thanks

**Comment by oscar3788** [comment]
Sorry, my mistake.
Special attention if somebody modifies the index and avi path...

**Comment by jameszah** [comment]
I have seen some problems downloading to android through chrome .... or maybe that is a different version that just writes to the sd card ... the main thing is to let the file be properly closed.
